name: openvidu-call E2E
on:
  push:
  #   paths:
  #     - 'openvidu-components-angular/**'
  #     - 'openvidu-browser/**'
  # pull_request:
  #   branches:
  #     - master

  repository_dispatch:
    types: [openvidu-components-angular]
  workflow_dispatch:

jobs:

  prepare_openvidu_angular:
    name: Prepare openvidu-angular
    runs-on: ubuntu-latest
    steps:
    - env:
        COMMIT_MESSAGE: ${{ github.event.client_payload.commit-message }}
        COMMIT_REF: ${{ github.event.client_payload.commit-ref }}
      run: echo Commit openvidu-components-angular
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build openvidu-browser and openvidu-angular
      env:
        BRANCH_NAME: ${{ github.event.client_payload.branch-name || 'master' }}
      run: |
        git clone -b ${BRANCH_NAME} https://github.com/OpenVidu/openvidu.git && \
        cd openvidu/openvidu-browser && \
        npm install && \
        npm run build && \
        npm pack && \
        mv openvidu-browser-*.tgz ../openvidu-components-angular && \
        cd ../openvidu-components-angular && \
        npm install openvidu-browser-*.tgz && \
        npm install && \
        npm run lib:build && \
        mv dist/openvidu-angular/openvidu-angular-*.tgz .
        tar -cvf artifacts.tar openvidu-angular-*.tgz openvidu-browser-*.tgz
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: openvidu/openvidu-components-angular/artifacts.tar

  e2e_test_with_authentication:
    needs: prepare_openvidu_angular
    name: Authentication E2E tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: actions/download-artifact@v3
      with:
        path: openvidu-call-front
    # - name: Run Selenium Chromedriver
    #   run: docker run -d --shm-size="4g" --network host selenium/standalone-chrome:106.0
    - name: Run Browserless Chrome
      run: docker run -d -p 3000:3000 --network host browserless/chrome:1.53-chrome-stable
    - name: Run openvidu-server-kms
      run: |
        docker run -p 4443:4443 --rm -d \
        -e OPENVIDU_SECRET=MY_SECRET \
        openvidu/openvidu-dev:latest
    - name: Install openvidu-angular and dependencies
      run: |
        cd openvidu-call-front && \
        tar -xvf artifacts/artifacts.tar && \
        npm install openvidu-angular-*.tgz && \
        npm install openvidu-browser*.tgz && \
        cd .. && \
        npm install --prefix openvidu-call-back
    - name: Build openvidu-call
      run: |
        npm run build --prefix openvidu-call-back && \
        npm run prod:build --prefix openvidu-call-front
    - name: Serve openvidu-call
      env:
        LAUNCH_MODE: CI
        CALL_OPENVIDU_CERTTYPE: selfsigned
      run: node openvidu-call-back/dist/app.js &
    - name: Run openvidu-call AUTH e2e
      run: npm run e2e:auth-ci --prefix openvidu-call-front


  e2e_test_without_authentication:
    needs: prepare_openvidu_angular
    name: No Authentication E2E tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: actions/download-artifact@v3
      with:
        path: openvidu-call-front
    # - name: Run Selenium Chromedriver
    #   run: docker run -d --shm-size="4g" --network host selenium/standalone-chrome:106.0
    - name: Run Browserless Chrome
      run: docker run -d -p 3000:3000 --network host browserless/chrome:1.53-chrome-stable
    - name: Run openvidu-server-kms
      run: |
        docker run -p 4443:4443 --rm -d \
        -e OPENVIDU_SECRET=MY_SECRET \
        openvidu/openvidu-dev:latest
    - name: Install openvidu-angular and dependencies
      run: |
        cd openvidu-call-front && \
        tar -xvf artifacts/artifacts.tar && \
        npm install openvidu-angular-*.tgz && \
        npm install openvidu-browser*.tgz && \
        cd .. && \
        npm install --prefix openvidu-call-back
    - name: Build openvidu-call
      run: |
        npm run build --prefix openvidu-call-back && \
        npm run prod:build --prefix openvidu-call-front

    - name: Serve openvidu-call
      env:
        LAUNCH_MODE: CI
        CALL_PRIVATE_ACCESS: DISABLED
        CALL_OPENVIDU_CERTTYPE: selfsigned
      run: node openvidu-call-back/dist/app.js &
    - name: Run openvidu-call BASIC e2e
      run: npm run e2e:basic-ci --prefix openvidu-call-front
